[package]
name = "debug-wasm-exported-rust-struct"
version = "0.1.0"
authors = ["Kate Hart <codehearts@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.54"
